name             'sprout-rbenv'
maintainer       'Pivotal Labs'
maintainer_email 'sprout-maintainers@googlegroups.com'
license          'MIT'
description      'Installs/Configures rbenv'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
supports         'mac_os_x'
depends          'sprout-base'
depends          'homebrew'
